[project]
authors = ["Wytamma Wirth <wytamma.wirth@me.com>"]
channels = ["conda-forge", "bioconda"]
name = "seqasia-phylo-env"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pip = ">=25.3,<26"
biopython = ">=1.86,<2"
mafft = ">=7.526,<8"
iqtree = ">=3.0.1,<4"
seqkit = ">=2.12.0,<3"
alv = ">=1.7.2,<2"
treetime = ">=0.11.4,<0.12"
matplotlib-inline = ">=0.2.1,<0.3"
rpy2 = ">=3.6.4,<4"
r = "*"
bioconductor-ggtree = ">=3.14.0,<4"
ipykernel = ">=7.1.0,<8"
